version: '2'

services:
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: host
#    ports:
#      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "89:80"

  apache2:
    depends_on:
      - mysql
    build: ./apache/
    links:
      - mysql
    restart: always
    ports:
      - "88:80"
    volumes:
      - ./apache/conf:/etc/apache2/sites-available/
      - /var/www:/var/www
      - ../log/apache2:/var/log/apache2
      - ../tmp:/tmp

  nginx:
    build: ./nginx/
    ports:
        - "80:80"
    links:
      - apache2
      - mysql
      - phpmyadmin
    restart: always
    volumes:
      - ./nginx/config:/etc/nginx/sites-enabled/
      - ../log/nginx:/var/log/nginx
      - /var/www:/var/www

volumes:
    db_data:
